# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  force
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
        mime_types:
            json: ['application/json', 'application/json;version=1.0', 'application/json;version=2.0']
    exception:
        enabled: true
        codes:
            {App\Exception\ResourceValidationException: 400}
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
    body_converter:
        enabled:  true
        validate: true
        validation_errors_argument: violations
    serializer:
        serialize_null: true
    versioning:
        enabled: true
        resolvers:
            media_type:
                enabled: true
                regex: '/(v|version)=(?P<version>[0-9\.]+)/'